Repository viur-framework/viur-vi, pull requests merged in 2019-03, with the labels that each got.

#24 removed unused preview widget
  actions/list.py
  widgets/__init__.py
  widgets/preview.py
Labels: proposal, v2.4

#26 improved handling of url in tree modules
  handler/tree.py
  network.py
  widgets/tree.py
Labels: enhancement, v2.4

#29 Moving the setPath call into the topbar, and saving path on the panes...
  admin.py
  handler/hierarchy.py
  handler/list.py
  handler/singleton.py
  handler/tree.py
  pane.py
  widgets/topbar.py
Labels: v2.4
